### ISSUE TITLE
The HTML selection & documentation are different

### ISSUE THREAD

**Issue by abdonrd** [mjbvz/vscode-lit-html#37]
The HTML file has the highlight the background color of the HTML tag name when selected and the documentation title is styled. In the JS file no.

![jul-03-2018 23-50-44](https://user-images.githubusercontent.com/1007051/42246184-f82470de-7f1b-11e8-896b-40d56a482dc7.gif)

**Comment by justinribeiro** [comment]
I'm away from desk today, but I'll get a patch worked up tomorrow.

**Comment by mjbvz** [comment]
Fixed by https://github.com/Microsoft/typescript-lit-html-plugin/pull/14

**Comment by abdonrd** [comment]
@mjbvz @justinribeiro I just tried and I think the problem is not solved.
With `VSCode 1.25.0` and `lit-html extension v1.5.2`, it still behaves the same as first post gif.

**Comment by justinribeiro** [comment]
It looks like the typescript-lit-html-plugin@0.4.2 is missing the fix; checked the generated `lib/typescript-lit-html-plugin.js`, and `translateHover` isn't what is currently merged in master.

**Comment by abdonrd** [comment]
I just tried the `v1.6.0` and the experience improves 👏

But it is not the same as in HTML files:
* Now the title (`<style>` in the GIF) appears separated, but with a different color.
* The selected tag highlight (background color) still does not exist.

![jul-07-2018 01-13-44](https://user-images.githubusercontent.com/1007051/42403684-31e35312-8183-11e8-8393-9392776c63da.gif)

**Comment by mjbvz** [comment]
Please open a separate issue for the highlighting support
